### ISSUE TITLE
"No test is available"... error

### ISSUE THREAD

**Issue by dockermaster** [Bumblebee/Bumblebee#100]
I tried both following the "Getting Started" wiki and also simply building the project itself however both give me the same error when I try to run the tests.

`No test is available in C:\Users\****\Desktop\Bumblebee-master\Bumblebee-master\src\Bumblebee.IntegrationTests\bin\Debug\Bumblebee.IntegrationTests.dll C:\Users\****\Desktop\Bumblebee-master\Bumblebee-master\src\Bumblebee\bin\Debug\Bumblebee.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.`

Any idea what am I missing?

**Comment by henryrawlins** [comment]
Hi dockermaster,
I've noticed you closed this issue.
I'm having the same problem. Can tell me about the solution? Thanks!
