### ISSUE TITLE
Stalefix state

### ISSUE THREAD

**Issue by jbiesta** [Bumblebee/Bumblebee#101]
Hi @toddmeinershagen 
Wasn't sure where to put this and didn't know how else I'd be able to contact you.
Firstly thanks for providing such a great library.
I wanted to get in touch with you to see what the state was of the Stalefix branch and whether there are any plans to merge it into master and get it released?
We're currently using it in our CI builds and have found it gives us a massive increase in speed on most of our tests so are very interested to see it getting merged in.

Thanks

**Comment by toddmeinershagen** [comment]
@jbiesta That's good feedback about the performance.  We want to release the 2nd version but we are lacking some documentation of the changes that will impact users and not having a lot of feedback.  (I tried to solicit input from the gitter feed, but I didn't get a lot of response.)   Would you be willing to help with the documentation??  

I am also wondering if we should upgrade the v1 to dotnet core before we merge the changes in.  Thoughts?

**Comment by jbiesta** [comment]
@toddmeinershagen We can certainly have a look at helping with the documentation side of things. 
In terms of upgrading to dotnet core my thoughts from an end user point of view would be that it would make sense to upgrade v1 first. That way if a user is upgrading to core they don't straight away have to adopt the new way of writing pageobjects and it'll give them more confidence that their upgrade to core has been successful rather than rewriting both the code and the tests at the same time.
Not sure how much work would be involved in upgrading v1.. I can see if I've got time to try and give it a go at some point if you're struggling for time?
Thanks

**Comment by toddmeinershagen** [comment]
@jbiesta Thanks for the feedback on the upgrade recommendation.  

As far as the documentation, I went ahead and moved the documentation over to the [readthedocs site](http://bumblebee-automation.readthedocs.io/en/latest/) to make it easier to navigate, search, and edit.  

If you have time, take a look and let me know if you have any thoughts about the new solution for documentation.  Once I go with the platform, we can begin updating the stalefix branch documentation.

**Comment by murtidash** [comment]
I'd be willing to spend some time helping with this as well. I upgraded to 2.0 for our initial implementation about 9 months ago and it's been going really well. I won't have a ton of time for the next few weeks but could pick up some specific tasks if there's a plan or tracker for the effort. 

In addition to the documentation having a 2.0 version of bumblebee.examples would probably be useful.

**Comment by toddmeinershagen** [comment]
@murtidash Thanks for being willing to help.  I moved the v1 and v2 documentation out to the [Read the Docs site](http://bumblebee-automation.readthedocs.io/en/latest/).  So, now people can go out and edit particular pages as pull requests.

I will also start adding tasks related to these issues so that people are aware  of what is outstanding.

**Comment by murtidash** [comment]
I've lost access to the stalefix readthedocs site, my readthedocs account is also 'murtidash'. Could you restore it when you get a chance.

Thanks

**Comment by toddmeinershagen** [comment]
@murtidash We have merged the stalefix branch into master.  So, the latest
version of the docs is for what we used to call stalefix.  The other
version is 1.3.1 which is the v1 code.

Hope that helps.  Let me know if there are still questions.

**Comment by toddmeinershagen** [comment]
@murtidash Be aware that we have officially release v2.  So, the only outstanding piece is updating the documentation.  I have already updated the Bumblee.Examples project to demonstrate how the new code works.  If you have questions or suggestions, let me know.
