### ISSUE TITLE
Could not load GPU driver

### ISSUE THREAD

**Issue by Yehun** [Bumblebee/Bumblebee#106]
After installing bumblebee, boot into xserver and no response from mouse and keyboard

Try to disable bumblebee from booting, enter graphics, and start bumblebee

Optirun is operating normally

Then after the shutdown and restart, follow the above steps, error: Could not load GPU driver

Try to modify the KernelDriver and xorg.conf.nvidia's Device in bumblebee.conf,

Then there is no egg. After reinstalling bumblebee or bumblebee-nvidia, it's OK.

The current bumblebee is still not very stable. I really want to understand what the problem is.

Hard work, developers, thank you guys

**Comment by toddmeinershagen** [comment]
@Yehun - I think you may have the wrong project.  I believe you are describing a GPU library for linux that you can find more info about [here](https://wiki.archlinux.org/index.php/bumblebee).  This project is for UI test automation on .NET.

**Comment by Yehun** [comment]
@toddmeinershagen I'm sorry, there's a wrong place to go, thank you.
