### ISSUE TITLE
Release 2.1.0 incompatible with 2.0.8

### ISSUE THREAD

**Issue by ccarmannt** [Bumblebee/Bumblebee#118]
When attempting to upgrade from 2.0.8-beta to 2.1.0-beta, this error was received:

````
You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework.
````

I tried updating all of our packages to target 4.6.2, but that only changed the version number in the error message.

**Comment by manofthetent** [comment]
@ccarmannt The 2.10 bumblebee automation component is a .NET standard component.  So, it should work with both .NET core and .NET framework 4.6.2 and above.

We have been successfully using it with the [Bumblebee.Examples project that is forked under my account](https://github.com/toddmeinershagen/Bumblebee.Examples).

The message that Visual Studio is giving you is telling you that the project you are trying to install the package is targeting 4.6.1.  You need to go to the properties of the project and select the Target Framework as 4.6.2 before installing the upgraded component.

If you are still not able to make it work, feel free to attach a zip file with the solution that can reproduce the issue and I can fix it and send it back.

**Comment by ccarmannt** [comment]
As I said, I've already updated all our packages to target 4.6.2:

````
<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
````

Is there something else that could cause this error message?

**Comment by manofthetent** [comment]
@ccarmant I think Visual Studio is being clear.  One of the projects that you are trying to install/upgrade the component is 4.6.1.  

If you want to zip the solution and attach, I can figure out which one.

**Comment by manofthetent** [comment]
@ccarmannt All I need is enough of the solution to reproduce your issue.  If you want to create a solution/project by itself targeting 4.6.2 and installing the Bumblebee.Automation component via NuGet it should produce the same issue -- if this is a problem with the component.  If not, then there is a problem with the configuration of your project/solution.

**Comment by ccarmannt** [comment]
Ok. I created a new project and tried importing Bumblebee 2.1.0. 

Here's the same error for 4.6.2:
````
Could not install package 'Bumblebee.Automation 2.1.0-beta'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
````

I've attached the zipped project.
[MyTestProject.zip](https://github.com/Bumblebee/Bumblebee/files/2138087/MyTestProject.zip)

**Comment by manofthetent** [comment]
I have attached the updated zip file with the Bumblebee.Automation 2.1.0-beta component successfully installed.

[MyTestProject.-installed.zip](https://github.com/Bumblebee/Bumblebee/files/2138133/MyTestProject.-installed.zip)

Below is a screenshot of the log as it was installing.  I don't see the same error message you are seeing locally.

![bumblebee-install-success](https://user-images.githubusercontent.com/20459187/41927625-5a6e8264-7938-11e8-927f-66fd39e46e37.PNG)

Are you using Visual Studio 2017 to do this?  If so, are you updated to the newest version of the NuGet extension for Visual Studio 2017?

**Comment by ccarmannt** [comment]
No, we're running VS 2015 here.

**Comment by toddmeinershagen** [comment]
It's probably time to upgrade.  Is there any reason why u cannot use the
latest?
