### ISSUE TITLE
"No test is available"... error #100 

### ISSUE THREAD

**Issue by henryrawlins** [Bumblebee/Bumblebee#119]
Dockermaster posted this on the 7th of March:

> I tried both following the "Getting Started" wiki and also simply building the project itself however both give me the same error when I try to run the tests.
> 
> No test is available in C:\Users\****\Desktop\Bumblebee-master\Bumblebee-master\src\Bumblebee.IntegrationTests\bin\Debug\Bumblebee.IntegrationTests.dll C:\Users\****\Desktop\Bumblebee-master\Bumblebee-master\src\Bumblebee\bin\Debug\Bumblebee.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
> 
> Any idea what am I missing?

This issue has been since closed by Dockermaster.
I'm facing the same issue. Can someone assist me on this?

Thanks!

**Comment by toddmeinershagen** [comment]
@henryrawlins Are you still experiencing this error running the tests in the project?  Make sure to install the NUnit3 test adapter to allow Visual Studio to discover the tests.  Also, there is more info you can find [here](https://github.com/nunit/nunit3-vs-adapter/issues/476) that might be of use to you.

**Comment by toddmeinershagen** [comment]
@henryrawlins - Are you still having issues running the tests locally??

**Comment by toddmeinershagen** [comment]
@henryrawlins I am going to close this issue since I haven't heard back from you based on my feedback.  If you still have an issue, feel free to add a new issue that refers to this issue.
