### ISSUE TITLE
Question - What is Dynamic<TBlock> For?

### ISSUE THREAD

**Issue by toddmeinershagen** [Bumblebee/Bumblebee#125]
Hello Todd,

I would like to ask for an example (business case) for the change of 25 Jun - introducing Dynamic type.

https://github.com/Bumblebee/Bumblebee/pull/117

In the description there is an issue mentioned:
> dynamic page elements would have to be public properties somewhere in the Page object model so that the framework could find and instantiate them. " 

We have in fact some such a public properties, however we do not see this as an issue.
Could you provide a short example "before" and "after" with some code, so we could understand the case which was problematic?

As for now - we are not sure how to get the public properties of such a generic class implementing IBlock... and how to eventually use this new type (Dynamic) in Bumblebee.

Thanks and Best Regards,
@mateusz-dobrowolny 

P.S.
We've finally migrated our project to 2.0.8 beta. :)

**Comment by toddmeinershagen** [comment]
@mateusz-dobrowolny 

Thanks for reaching out.

You are correct that ```Dynamic<TBlock>``` is not necessarily needed for the framework to work.  If you have a Block that you click to from a ```Clickable<TBlock>```, the underlying code uses a method called ```FindRelated<TBlock>()``` which searches the parental hierarchy for a public property of that type to instantiate.  So, there must be a public property in the chain of ancestors (parent, grandparent, etc.) with a property of that ```TBlock``` type to work.

The one scenario that does not work well here are hidden dialogs or forms that appear as the result of a ```Clickable<TBlock>```.  In that case, you don't want the QA automation people to go straight to the form.

```csharp
Parent
  .HiddenForm
  .TaskName.EnterText("Todd");
```

Instead, you want to make sure that they click to it.

```csharp
Parent
  .ShowHiddenForm
  .Click()
  .TaskName
  .EnterText("Todd");
```

The ```Dynamic<TBlock>``` allows us to make that property public, but does not allow the automation people to do anything if they navigate straight to that property.  It does not expose any other properties or methods.

A good example is found in [Bumblebee.Examples](https://github.com/toddmeinershagen/Bumblebee.Examples/blob/master/src/Bumblebee.Examples/Bumblebee.Examples.Web.Pages/Nirvana/LoggedInPage.cs) project.  (Note - this is only updated in my fork of the repo right now.  I am working on pushing it to the main project and updating the documentation.)

Hope that helps.

**Comment by mateusz-dobrowolny** [comment]
Hi Todd,

Thanks, that helps.

We've migrated to new Bumblebee (still 2.0.8), however we also made a lot
of changes in our modell, so it took long.
Still we have some issues, and my colleague found a bug, so we keep staying
in touch ;)

Have a good day!

Best Regards,
Mateusz
