### ISSUE TITLE
Is it a good idea to have Bumblebee TypeScript version?

### ISSUE THREAD

**Issue by aaronamm** [Bumblebee/Bumblebee#126]
Dear Todd

Thank you so much for creating Bumblebee. It is a very useful project.
I use it a lot in my professional work.

However, I found myself the project is in C# and it is hard for me to convince other people to use this project, especially fronted developer who understand JavaScript.
I want those people to start using automated tests instead of doing manual test.

Therefore, I came up with an idea to convert Bumblebee to TypeScript and contribute it to Bumblebee.
What is your opinion to this idea, will you able to merge it as part of the main project?
If so I can start converting Bubble C# version to have the same interface and make a PR  to you.
 You can help me prepare a new repository for, e.g. Bumblebee.ts or any other cooler names. 

Best wishes,

**Comment by toddmeinershagen** [comment]
Hey @aaronamm,

Sorry it took me a bit to get back to you on this.  I appreciate your interest in furthering the Bumblebee project.  Certainly, the ability to develop page objects is key to making automated functional tests maintainable long-term no matter what language.

I am curious about the type script idea -- and I don't want to hold you up from making progress.

Why don't you create the new repo under your account - maybe call it Bumblebee.TypeScript - and begin working on it.  We could even release an npm package from that repository for the time being.  In the future, as more people begin to use it, we can move the repo under the Bumblebee organization.  That is how I handled some other projects I worked on for NLog.

What do you think?

**Comment by aaronamm** [comment]
@toddmeinershagen  Thank you for your reply.
That's a good idea. I will do what you suggested.
