### ISSUE TITLE
Latest stable Bumblebee does not work with latest stable Selenium.Webdriver

### ISSUE THREAD

**Issue by mide1234** [Bumblebee/Bumblebee#127]
Hi,

the current stable version of Bumblebee 1.3.1 does not work with Selenium.WebDriver 3.14.0 (because of the breaking changes in WebDriver e.g. timeouts are now set via properties instead of methods). I believe this is known. 

By creating this issue I am trying to find out when will Bumblebee work with current WebDriver. The beta version of Bumblebee seems to contain the needed fixes but it is still a beta so one cannot really use it to produce a stable package of his/here work (automation framework in my case).

Any information are welcomed.

Thanks.

**Comment by toddmeinershagen** [comment]
@mide1234We addressed this in the v2 code base which is still in pre-release, but it is basically finished without the documentation being updated.

I wasn't planning to make any further updates to the v1 package after upgrading it to the .NET standard to support .NET core.  

Right now there are a couple of options:  1) upgrade to the pre-release version (there may be some changes you have to make to your code or 2) leave your Selenium version at the version before the breaking change.  

Thoughts?

**Comment by toddmeinershagen** [comment]
@mide1234 I see.  I didn't realize that you were maintaining a framework as a wrapper to Bumblebee.  In that case, you would need to make your package Pre-Release as well.  I don't know if that is an issue with your organization.  Is that a possibility?

**Comment by mide1234** [comment]
@toddmeinershagen Yeah, the framework has lot of functionality and among it it works as a wrapper to Bumblebee. Sadly I cannot make my package as pre-release, people in our organization would not consume it.

**Comment by toddmeinershagen** [comment]
I wanted you to know that we release v2 of Bumblebee.Automation out of beta
this morning.  So, it is a full release that you can leverage now.

In addition, we added a HeadlessChrome driver environment and
HeadlessChromeDriver class that you might find useful in your own
automation.

Hope it helps,


Todd
