### ISSUE TITLE
Could not load type 'OpenQA.Selenium.PhantomJS.PhantomJSDriver' from assembly WebDriver

### ISSUE THREAD

**Issue by mide1234** [Bumblebee/Bumblebee#128]
Hey,

I am playing a bit with the latest prerelease version of Bumblebee and it looks like it still refers to the PhantomJS type while the WebDriver dropped the support in 3.14.0 - see their [changelog](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/dotnet/CHANGELOG).

Steps to replicate:
```C#
[Test]
public void SeleniumLoadTest()
{
	var windsorContainer = new WindsorContainer();
	var filter = new AssemblyFilter(".");
	filter.FilterByName(name => name.Name.Equals("Bumblebee"));

	try
	{
		windsorContainer.Install(FromAssembly.InDirectory(filter));
	}
	catch (Exception e)
	{   
		//throws "Could not load type 'OpenQA.Selenium.PhantomJS.PhantomJSDriver' from assembly 'WebDriver, Version=3.14.0.0, Culture=neutral, PublicKeyToken=null'"
	}
}
```

_Note: The test above assumes that there is Bumblebee and WebDriver dlls in the bin folder._

Would it be an issue to drop support for PhantomJS and remove all the references to it in the code?

**Comment by toddmeinershagen** [comment]
@mide1234 Are you using the PhantomJS driver environment in your code?

**Comment by toddmeinershagen** [comment]
@mide1234 I updated the Bumblebee.Examples to the latest 2.1.2 of Bumblebee.Automation and the latest Selenium.WebDriver 3.141.0 to see if it creates an issue with PhantomJS driver.  As long as you do not use the PhantomJS driver environment in your code, it should not get that error.  They marked it as obsolete, but they still have the PhantomJSDriver existing for binding purposes.  

We are leaving the support in the Bumblebee framework for now in case others are using the lower version of Selenium.WebDriver.  It should not cause issues with the later versions as long as you do not try to instantiate it.
