### ISSUE TITLE
Sign the Bumblebee assembly with strong name key

### ISSUE THREAD

**Issue by monkog** [Bumblebee/Bumblebee#133]
Assemblies signed with snk can only reference other assemblies that are signed with the snk as well. Please sign the Bumblebee assembly to allow referencing it by signed assemblies.

**Comment by toddmeinershagen** [comment]
@monkog Thanks for your suggestion.  

I have explored strongly signing my assembly in the past, but unfortunately, Selenium is not strongly signed.  So, until they decide to strongly sign their package, I will be unable to do that for our project.

Feel free to reach out to the good folks over at Selenium, though, to see if they are willing.  My guess is that they either have a dependency on something that is not currently strongly signed or they have a philosophical reason for not wanting to strongly sign theirs.

Hope that helps.
