### ISSUE TITLE
EnterText() and AppendText() methods does not support colon

### ISSUE THREAD

**Issue by blackyboo** [Bumblebee/Bumblebee#134]
I need to fill text containing colon character to some field. It is not possible to use EnterText() or AppendText() methods, because when I use them, the colon character is skipped and the text is filled without it. 
I tried to fill in the character separately using the Press() method, but there is no colon character in Bumblebee.Key.cs (https://github.com/Bumblebee/Bumblebee/blob/master/src/Bumblebee/Key.cs)

**Comment by toddmeinershagen** [comment]
@blackyboo Sorry it took me a few days to get to this.  I don't think this is possible.  We are wrapping Selenium's [Keys feature] and it doesn't look like they support the Keys.Colon either.  It might have to do with html encoding limitations.  

If you want to issue a pull request with a potential solution, I am open to pulling it in.
