### ISSUE TITLE
waiting for ajax completion

### ISSUE THREAD

**Issue by circa1741** [Bumblebee/Bumblebee#27]
it would be nice to have something like:

.WaitFor.AjaxCallsToComplete(TimeSpan.FromSeconds(8))
or
.WaitForAjaxCallsToComplete(TimeSpan.FromSeconds(8))

There could be a configurable default timeout that is overrideable.

**Comment by toddmeinershagen** [comment]
Since there is no easy way to check if any given ajax call has completed, checking some state change in the DOM (as suggested by Dru), makes sense.  For now, we are marking this as closed and as a won't fix issue.
