### ISSUE TITLE
Session:  Add Screen Capture

### ISSUE THREAD

**Issue by toddmeinershagen** [Bumblebee/Bumblebee#41]
Selenium offers the ability to capture the screen.  It would be helpful to have this functionality so that I could do the following:

```csharp
var session = Threaded<Session>.With<InternetExplorer>();
session.CaptureScreen();
```

The default location could be the executing directory and if the user wants to override this location, they could override some settings.  For instance,

```csharp
var settings = new Settings { ScreenCapturePath = "C:\Temp" };
var session = Threaded<Session>.With<InternetExplorer>(settings);
session.CaptureScreen();
\\output to the C:\Temp directory
```

**Comment by toddmeinershagen** [comment]
I added this to latest commit (2015-04-19).  Will release on the next push to NuGet.

**Comment by forcewake** [comment]
Hello @toddmeinershagen 
Could you please say when will be next push to NuGet?

**Comment by toddmeinershagen** [comment]
@forcewake - I can push what we currently have.  We added the ability to capture on verification failure  and I was going to add another feature.  But now would be a good time to make a cut.  I'll try to do that today.

**Comment by forcewake** [comment]
@toddmeinershagen thanks!
It will be cool.

**Comment by toddmeinershagen** [comment]
This is part of release 1.2.0
