### ISSUE TITLE
Handling page redirects 

### ISSUE THREAD

**Issue by avishnyakov** [Bumblebee/Bumblebee#48]
Hello team, 

First of all, thanks for a great job you've done. API is extremely easy to get started with, wiki rocks and the overall impression is awesome.

However, with auth/login/logout scenarios we page redirects.
For instance, we need to fill out a form, but first we need to login. Once we put username and password, a login page does multiple redirects, and Bumblebee does not seem to wait/handle it.

Not sure what's the right way to wait until all redirects are done, or wait until a particular condition is true. 

What might be a solution to handle/wait page redirects?

**Comment by toddmeinershagen** [comment]
Thanks for the feedback.  Good to hear that you like the api.  

Waiting for elements to exist with a timeout in the constructor of the next page block should handle what you are looking for in logging in.  There is an example in the [bumblebee.example](https://github.com/Bumblebee/Bumblebee.Examples) project for logging in to nirvana and reddit.  

Check it out.  Let me know if u have other questions.

**Comment by avishnyakov** [comment]
Seems to be just about right. Will give another go, many thanks!
