### ISSUE TITLE
Alter the way elements are found using jQuery

### ISSUE THREAD

**Issue by chrisblock** [Bumblebee/Bumblebee#60]
Currently, there is an extension method off the `IWebDriver` type that allows for finding elements via jQuery (assuming it is loaded).

It would be great if we could refactor this to have a more standardized usage, leveraging the Selenium `By` functionality.

For example, creating a `ByJQuery` type and also allowing for `By.JQuery("#id li:eq(1)")`.

**Comment by toddmeinershagen** [comment]
This was release as part of v2.
