### ISSUE TITLE
Determining if jQuery is present on the page

### ISSUE THREAD

**Issue by chrisblock** [Bumblebee/Bumblebee#61]
To go along with finding elements using jQuery (#60), I think it would be a good idea to provide a function that will allow the user to determine if jQuery is even present on the page.

Ideally, these methods would be sequestered off on their own in a separate namespace so that users are not burdened with seeing them if they are not using jQuery.

So I guess an extension method off of the `Session` type like `HasJQuery` would, in my mind, be optimal.

**Comment by toddmeinershagen** [comment]
This was released as part of v2.
