### ISSUE TITLE
Stale Element Reference Exception

### ISSUE THREAD

**Issue by ashokkumarg** [Bumblebee/Bumblebee#96]
Result StackTrace:  
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElementById(String id)
   at OpenQA.Selenium.By.<>c__DisplayClass2.<Id>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElement(By by)
   at Bumblebee.Implementation.Block.FindElement(By by)
   at Bumblebee.Implementation.Block.get_Tag()
   at Bumblebee.Implementation.WebBlock.<get_Tag>b__0(IWebDriver driver)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at Bumblebee.Implementation.WebBlock.get_Tag()
   at Bumblebee.Implementation.Block.FindElement(By by)
   at Bumblebee.Implementation.Clickable`1..ctor(IBlock parent, By by)

Result Message: OpenQA.Selenium.StaleElementReferenceException : Element not found in the cache - perhaps the page has changed since it was looked up

**Comment by ashokkumarg** [comment]
I have two pages called login and lead. In the main class under one threaded session i wrote the login functionality. Then on the threaded session I wrote lead functionality. When the page navigates from login to lead. I get the stale reference exception.

But, when i write the login and lead under one threaded session it works fine.


**Code:**
**Main Class**
```
namespace Practise_Project.Test_Engine
{
    [TestFixture]
    public class Engine
    {
        [SetUp]
        public void setUp()
        {
            Threaded<Session>
                .With<Firefox>()
                .NavigateTo<Login>(URL);
        }

        [TearDown]
        public void tearDown()
        {
            Threaded<Session>
                .End();
        }

        [Test]
        public void testOne()
        {
            Threaded<Session>
                  .CurrentBlock<Login>()
                  .Username.EnterText(username)
                  .Password.EnterText(password)
                  .button.Click();

            Threaded<Session>
                  .CurrentBlock<Lead>()
                  .leadtab.Click();

            Threaded<Session>
                .CurrentBlock<LeadCreation>()
                .newlead.Click()
                .firstname.EnterText("Ashok")
                .lastname.EnterText("Kumar");
            
        }
    }
```

**Login**
```
namespace Practise_Project.Pages
{
   public class Login:WebPage
    {
        public Login(Session session) : base(session)
        {

        }
        public ITextField<Login> Username => new TextField<Login>(this, By.Id("username"));
        public ITextField<Login> Password => new TextField<Login>(this, By.Id("password"));
        public IClickable<Login> button => new Clickable<Login>(this, By.Id("Login"));
    }
}
```

**Lead**
```
namespace Practise_Project.Pages
{
    public class Lead:WebBlock
    {
        public Lead(IBlock parent)
            : base(parent, By.Id("phSearchInput"), TimeSpan.FromSeconds(5))
        {
        }

        public Lead(Session session)
            : base(
                Page.Create<Login>(session),
                By.Id("phSearchInput"), TimeSpan.FromSeconds(5))
        {
        }

        public LeadCreation LeadCreation => new LeadCreation(Session);

        public Clickable<Lead> leadtab => new Clickable<Lead>(this, By.CssSelector("a[title^=Leads]"));
       
    }
}
```

**Comment by toddmeinershagen** [comment]
A couple of thoughts/questions;

1.  Is this using the alpha 2.x version of Bumblebee?
1.  You should probably use .CurrentPage instead of CurrentBlock, if that
is a page you are referencing.
2.  You don't need to use the .CurrentBlock/Page properties if you are in
the same method.  You can either keep using the fluent notation or assign a
local variable to the page.

Threaded<Session>
  .CurrentBlock<Login>()
  .Username.EnterText(username)
  .Password.EnterText(password)
  .button.Click()
  .leadtab.Click();


or

var login = Threaded<Session>
  .CurrentBlock<Login>()
  .Username.EnterText(username)
  .Password.EnterText(password)
  .button.Click();


login.leadtab.Click();


Todd

**Comment by toddmeinershagen** [comment]
@ashokkumarg Was your issue resolved with my last response?

**Comment by ashokkumarg** [comment]
@toddmeinershagen Sorry for the very late response. Yes the solution is working good.
